<?php

namespace App\Console\Commands;

use App\Helpers\CustomerHelper;
use App\Models\Tag;
use Illuminate\Console\Command;
use App\Models\User;
use App\Models\Customer;
use App\Models\UserDetail;
use App\Models\CustomerAddress;
use App\Models\SurvivorNumber;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\Storage;

class SeedTestUsers extends Command
{
    protected $signature = 'seed:test-users {--membership=} {--count=5}';
    protected $description = 'Generate test users by membership tier for customer service testing';

    public function handle()
    {
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
        $faker = Faker::create();
        $membership = strtolower($this->option('membership') ?? 'none');
        $count = (int) $this->option('count');

        $headers = ['Survivor #', 'Name', 'LastName', 'DOB', 'Email', 'Username', 'Membership'];
        $rows = [];

        $csvContent = implode(',', $headers) . "\n";

        if ($membership === 'none') {
            $membershipType = null;
        } else {
            $membershipTypeName = ucfirst($membership);
            $membershipType = \App\Models\MembershipType::where('name', $membershipTypeName)->first();

            if (!$membershipType) {
                $this->error("Error, '$membershipTypeName' not found.");
                return;
            }
        }

        for ($i = 1; $i <= $count; $i++) {

            $email = '';
            $username = '';
            $attempt = 1;
            do {
                $email = "booking+test_user_{$membership}_{$attempt}@70000tons.com";
                $username = "testuser_{$membership}_{$attempt}";
                $exists = User::where('email', $email)->exists();
                $attempt++;
            } while ($exists);

            $user = User::create([
                'email' => $email,
                'username' => $username,
                'password' => Hash::make('password'),
                'organization_id' => env('ORGANIZATION_ID', 1),
            ]);

            $userDetail = UserDetail::create([
                'user_id' => $user->id,
                'gender' => $faker->randomElement(['M', 'F']),
                'first_name' => 'TEST ' . strtoupper($faker->firstName),
                'middle_name' => strtoupper($faker->firstName),
                'last_name' => strtoupper($faker->lastName),
                'dob' => $faker->date(),
                'citizenship' => $faker->countryISOAlpha3(),
                'phone' => $faker->e164PhoneNumber(),
                'avatar' => $faker->imageUrl(),
                'emergency_c_name' => $faker->name,
                'emergency_c_phone' => $faker->e164PhoneNumber(),
                'language' => $faker->randomElement(['es', 'de', 'en']),
            ]);

            CustomerAddress::create([
                'user_id' => $user->id,
                'address_first' => $faker->streetAddress,
                'address_second' => $faker->secondaryAddress,
                'city' => $faker->city,
                'state' => $faker->state,
                'postal_code' => $faker->postcode,
                'country' => $faker->countryISOAlpha3(),
            ]);
            $survivorNumber = CustomerHelper::generateSurvivorNumber($user->id);
            SurvivorNumber::create([
                'user_id' => $user->id,
                'survivor_number' => $survivorNumber,
            ]);

            if ($membershipType) {
                $user->membership()->create([
                    'user_id' => $user->id,
                    'membership_id' => $membershipType->id,
                ]);
            }   

            setPermissionsTeamId(1);
            $user->assignRole('Customer');
            
            // Attach TEST tag to the customer
            $testTag = Tag::firstOrCreate(
                ['name' => 'TEST', 'type' => 'customer'],
                [
                    'description' => 'Test user generated by SeedTestUsers command',
                    'color' => '#ff9800'
                ]
            );  
            
            $customer = Customer::find($user->id);
            $customer->tags()->sync([$testTag->id]);  

            $rows[] = [$survivorNumber, $userDetail->first_name, $userDetail->last_name, $userDetail->dob, $email, $username, ucfirst($membership)];
            $csvContent .= implode(',', [$survivorNumber, $userDetail->first_name, $userDetail->last_name, $userDetail->dob, $email, $username, $membership]) . "\n";
        }

        $this->table($headers, $rows);
        $filename = 'test_users_' . strtolower($membership) . '_' . now()->format('Y-m-d_Hi') . '.csv';
        Storage::disk('local')->put($filename, $csvContent);
        $this->info('✔ Test users generated and saved to storage/app/test_users.csv');
    }
}
