<?php

namespace App\Enums\GlobalLog;

enum LogActionBooking: string
{
    case AGEND_ID_CHANGED = 'AGEND_ID_CHANGED';
    case BED_CONFIG_CHANGED = 'BED_CONFIG_CHANGED';
    case CABIN_ID_CHANGED = 'CABIN_ID_CHANGED';
    case CABIN_NUMBER_CHANGED = 'CABIN_NUMBER_CHANGED';
    case CUSTOMER_ID_CHANGED = 'CUSTOMER_ID_CHANGED';
    case PAYMENT_PLAN_CHANGED = 'PAYMENT_PLAN_CHANGED';
    case BOOKING_CANCELLED = 'BOOKING_CANCELLED';
    case BOOKING_CODE_CHANGED = 'BOOKING_CODE_CHANGED';
    case BOOKING_CREATED = 'BOOKING_CREATED';
    case REQUEST_ID_CHANGED = 'REQUEST_ID_CHANGED';
    case TAG_ATTACHED = 'TAG_ATTACHED';
    case TAG_DETACHED = 'TAG_DETACHED';
    case INVOICE_GENERATED = 'INVOICE_GENERATED'; // not implemented yet
    case EVENT_ID_CHANGED = 'EVENT_ID_CHANGED';
    case SINGLE_OCCUPANCY_CHANGED = 'SINGLE_OCCUPANCY_CHANGED';
    case STATUS_CHANGED = 'STATUS_CHANGED';
    case ADJUSTMENT_ADDED = 'ADJUSTMENT_ADDED';
    case ADJUSTMENT_DELETED = 'ADJUSTMENT_DELETED';
    case ADJUSTMENT_UPDATED = 'ADJUSTMENT_UPDATED';
    case PAYMENT_CREATED = 'PAYMENT_CREATED';
    case SPLIT_PAYMENT_CREATED = 'SPLIT_PAYMENT_CREATED';
    case TRANSFER_PAYMENT_CREATED = 'TRANSFER_PAYMENT_CREATED';
    case PAYMENT_DELETED = 'PAYMENT_DELETED';
    case SPLIT_PAYMENT_DELETED = 'SPLIT_PAYMENT_DELETED';
    case TRANSFER_PAYMENT_DELETED = 'TRANSFER_PAYMENT_DELETED';
    case FEE_CREATED = 'FEE_CREATED';
    case FEE_DELETED = 'FEE_DELETED';
    case DISCOUNT_CREATED = 'DISCOUNT_CREATED';
    case DISCOUNT_DELETED = 'DISCOUNT_DELETED';
    case BOOKING_OPENED = 'BOOKING_OPENED';
    case AGENT_SESSION_CREATED = 'AGENT_SESSION_CREATED';
    case AGENT_SESSION_UPDATED = 'AGENT_SESSION_UPDATED';
    case AGENT_SESSION_DELETED = 'AGENT_SESSION_DELETED';
    case ONBOARD_CREDIT_CREATED = 'ONBOARD_CREDIT_CREATED';
    case ONBOARD_CREDIT_DELETED = 'ONBOARD_CREDIT_DELETED';
    case EMAIL_SENT = 'EMAIL_SENT';
    case SET_EMPTY_SEAT = 'SET_EMPTY_SEAT';
    case UNSET_EMPTY_SEAT = 'UNSET_EMPTY_SEAT';
    case PASSENGER_UPDATED = 'PASSENGER_UPDATED';
    case PASSENGER_INVITATION_DELETED = 'PASSENGER_INVITATION_DELETED';
    case PASSENGER_RELEASED = 'PASSENGER_RELEASED';
    case BOOKING_REQUEST_ID_CHANGED = 'BOOKING_REQUEST_ID_CHANGED';
    case BOOKING_DELETED = 'BOOKING_DELETED';
    case PAYMENT_REMINDER_SENT = 'PAYMENT_REMINDER_SENT';
    case SYSTEM_TRANSACTION_RECEIVED = 'SYSTEM_TRANSACTION_RECEIVED';
    case EMAIL_TO_CUSTOMERS = 'EMAIL_TO_CUSTOMERS';
    case CABIN_UPGRADE = 'CABIN_UPGRADE';
    case CABIN_SET_TO_RESERVED = 'CABIN_SET_TO_RESERVED';

    //From SPA Front
    case USER_SET_EMPTY_SEAT = 'USER_SET_EMPTY_SEAT';
    case USER_REMOVED_EMPTY_SEAT = 'USER_REMOVED_EMPTY_SEAT';
    case USER_ADD_PASSENGER_MANUALLY = 'USER_ADD_PASSENGER_MANUALLY';
    case USER_CANCELLED_INVITATION = 'USER_CANCELLED_INVITATION';
    case USER_RESET_PASSENGER_SEAT = 'USER_RESET_PASSENGER_SEAT';
    case USER_ADD_PASSENGER_VIA_EMAIL = 'USER_ADD_PASSENGER_VIA_EMAIL';

    //AutoTag
    case SYSTEM_REMOVED_OVERDUE_TAG = 'SYSTEM_REMOVED_OVERDUE_TAG';
    case SYSTEM_ADDED_OVERDUE_TAG = 'SYSTEM_ADDED_OVERDUE_TAG';
    case SYSTEM_ADDED_MISSING_PAX_TAG = 'SYSTEM_ADDED_MISSING_PAX_TAG';
    case SYSTEM_REMOVED_MISSING_PAX_TAG = 'SYSTEM_REMOVED_MISSING_PAX_TAG';
}
