<?php

namespace App\Enums\GlobalLog;

enum LogActionCabin: string {
    case INVENTORY_CHANGED = 'INVENTORY_CHANGED';
    case STATUS_CHANGED = 'STATUS_CHANGED';
    case CATEGORY_CHANGED = 'CATEGORY_CHANGED';
    case TAG_UPDATED = 'TAG_UPDATED';
    case NOTES_UPDATED = 'NOTES_UPDATED';
    case TYPE_CHANGED = 'TYPE_CHANGED';
    case CABIN_NUMBER_CHANGED = 'CABIN_NUMBER_CHANGED';
    case DECK_CHANGED = 'DECK_CHANGED';
    case INTERNAL_NOTES_UPDATED = 'INTERNAL_NOTES_UPDATED';
    case TOTAL_BERTHS_CHANGED = 'TOTAL_BERTHS_CHANGED';
    case UPPER_BERTHS_CHANGED = 'UPPER_BERTHS_CHANGED';
    case LOWER_BED_TYPE_1_CHANGED = 'LOWER_BED_TYPE_1_CHANGED';
    case LOWER_BED_TYPE_2_CHANGED = 'LOWER_BED_TYPE_2_CHANGED';
    case ACCESSIBILITY_CHANGED = 'ACCESSIBILITY_CHANGED';
    case OBSTRUCTED_VIEW_CHANGED = 'OBSTRUCTED_VIEW_CHANGED';
    case BALCONY_CHANGED = 'BALCONY_CHANGED';
    case CONNECTS_WITH_CHANGED = 'CONNECTS_WITH_CHANGED';
    case LOCATION_CHANGED = 'LOCATION_CHANGED';
}
