<?php

declare(strict_types=1);

use App\Models\Tag;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use PhpParser\Node\Expr\AssignOp\Mod;

if (! function_exists('createOrGetTag')) {
    /**
     * get or create a Tag by name and type.
     *
     * @param  non-empty-string  $name   Name of the tag (it normalizes to UPPER)
     * @param  non-empty-string  $type   Type/area of the tag (e.g., 'BOOKING', 'USER')
     * @param  string|null       $color  Hex (ex: #000000). default #000000
     * @param  string|null       $description Description; if null, it auto-generates
     * @return Tag
     */
    function createOrGetTag(string $name, string $type, ?string $color = '#000000', ?string $description = null): Tag
    {
        $normalizedName = Str::upper(trim($name));
        $normalizedType = Str::upper(trim($type));
        $hexColor       = $color ? strtoupper($color) : '#000000';

        /** @var Tag $tag */
        $tag = Tag::firstOrCreate(
            ['name' => $normalizedName, 'type' => $normalizedType],
            [
                'id'          => (string) Str::uuid(),
                'color'       => $hexColor,
                'description' => $description ?? "Tag autogenerated for {$normalizedType}",
            ]
        );

        return $tag;
    }
}

if (! function_exists('hasTag')) {
    /**
     * Exists a Tag by name and type?
     */
    function hasTag(string $name, string $type): bool
    {
        return Tag::query()
            ->where('name', Str::upper(trim($name)))
            ->where('type', Str::upper(trim($type)))
            ->exists();
    }
}

if (! function_exists('attachTag')) {
    /**
     * Attach a Tag to a Model (e.g., Booking, User).
     *
     * Requires a relation $model->tags() (belongsToMany) or a compatible method.
     *
     * @return Tag Associated Tag
     */
    function attachTag(Model $model, string $name, string $type, ?string $color = '#000000', ?string $description = null): Tag
    {
        $tag = createOrGetTag($name, $type, $color, $description);

        if (method_exists($model, 'tags')) {
            $model->tags()->syncWithoutDetaching([$tag->id]);
            return $tag;
        }

        if (method_exists($model, 'attachTags')) {
            $model->attachTags([$tag->id]);
            return $tag;
        }

        throw new RuntimeException(sprintf(
            "Model %s does not expose 'tags()' relation nor 'attachTags()' method.",
            get_class($model)
        ));
    }

    if (! function_exists('removeTag')) {
        /**
         * Deattach a Tag from a Model (e.g., Booking, User).
         *
         * @param  Model  $model   Eloquent model instance (e.g., Booking, User)
         * @param  string $name    Tag name (ej: 'OVERDUE')
         * @param  string $type    Type/area of the tag (e.g., 'BOOKING', 'USER')   
         * @return bool            True if the tag was removed, false if the tag did not exist on the model.
         */
        function removeTag(Model $model, string $name, string $type): bool
        {
            $normalizedName = Str::upper(trim($name));
            $normalizedType = Str::upper(trim($type));

            /** @var Tag|null $tag */
            $tag = Tag::where('name', $normalizedName)
                ->where('type', $normalizedType)
                ->first();

            if (! $tag) {
                return false;
            }
            if (method_exists($model, 'tags')) {
                $detached = $model->tags()->detach($tag->id);
                return $detached > 0;
            }

            if (method_exists($model, 'detachTags')) {
                $model->detachTags([$tag->id]);
                return true;
            }

            throw new RuntimeException(sprintf(
                'Model %s does not expose tags() relation nor detachTags() method.',
                get_class($model)
            ));
        }
    }
}
