<?php
declare(strict_types=1);

namespace App\Helpers;

use App\Models\Tag;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use RuntimeException;

final class TagHelper {
    /** @return non-empty-string */
    private static function normalizeName(string $name): string {
        $n = Str::upper(trim($name));
        if ($n === '') {
            throw new \InvalidArgumentException('Tag name cannot be empty.');
        }
        return $n;
    }

    /** @return non-empty-string */
    private static function normalizeType(string $type): string {
        $t = Str::lower(trim($type));
        if ($t === '') {
            throw new \InvalidArgumentException('Tag type cannot be empty.');
        }
        return $t;
    }

    private static function isValidUuid(?string $id): bool {
        if (!$id) {
            return false;
        }
        // Accepts UUID v1–v5
        return (bool) preg_match(
            '/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/',
            $id,
        );
    }

    /** @return string */
    private static function normalizeHexColor(?string $hex): string {
        $hex = strtoupper($hex ?: '#000000');
        // Accepts #RGB, #RRGGBB, #RRGGBBAA
        if (!preg_match('/^#([0-9A-F]{3}|[0-9A-F]{6}|[0-9A-F]{8})$/', $hex)) {
            return '#000000';
        }
        return $hex;
    }

    /**
     * Create or retrieve a Tag by (name, type).
     * @param  non-empty-string $name
     * @param  non-empty-string $type
     */
    public static function createOrGetTag(
        string $name,
        string $type,
        ?string $color = '#000000',
        ?string $description = null,
    ): Tag {
        $normalizedName = self::normalizeName($name);
        $normalizedType = self::normalizeType($type);
        $hexColor = self::normalizeHexColor($color);

        /** @var Tag $tag */
        $tag = Tag::firstOrCreate(
            ['name' => $normalizedName, 'type' => $normalizedType],
            [
                'id' => (string) Str::uuid(),
                'color' => $hexColor,
                'description' => $description ?? "Autogenerated tag for {$normalizedType}",
            ],
        );

        return $tag;
    }

    /**
     * Does a tag exist in the DB by name and type?
     */
    public static function hasTag(string $name, string $type): bool {
        return Tag::query()
            ->where('name', self::normalizeName($name))
            ->where('type', self::normalizeType($type))
            ->exists();
    }

    /**
     * Is the given model currently tagged with this name/type?
     */
    public static function isTagged(Model $model, string $name, string $type): bool {
        $normalizedName = self::normalizeName($name);
        $normalizedType = self::normalizeType($type);

        if (!method_exists($model, 'tags')) {
            throw new RuntimeException(sprintf("Model %s does not expose a 'tags()' relation.", get_class($model)));
        }

        return $model->tags()->where('tags.name', $normalizedName)->where('tags.type', $normalizedType)->exists();
    }

    /**
     * Attach a tag to a model (idempotent).
     * Returns the Tag; safe to call multiple times.
     */
    public static function attachTag(
        Model $model,
        string $name,
        string $type,
        ?string $color = '#000000',
        ?string $description = null,
    ): Tag {
        $tag = self::createOrGetTag($name, $type, $color, $description);

        if (!method_exists($model, 'tags') && !method_exists($model, 'attachTags')) {
            throw new RuntimeException(
                sprintf("Model %s does not expose 'tags()' relation nor 'attachTags()' method.", get_class($model)),
            );
        }

        if (method_exists($model, 'tags')) {
            $model->tags()->syncWithoutDetaching([$tag->id]);
            return $tag;
        }

        // Fallback to custom method
        $model->attachTags([$tag->id]);
        return $tag;
    }

    /**
     * Remove a tag from a model.
     * Returns true if removed, false if it wasn’t attached.
     */
    public static function removeTag(Model $model, string $name, string $type): bool {
        $normalizedName = self::normalizeName($name);
        $normalizedType = self::normalizeType($type);

        /** @var Tag|null $tag */
        $tag = Tag::where('name', $normalizedName)->where('type', $normalizedType)->first();

        if (!$tag) {
            return false; // Tag does not exist
        }

        if (!self::isValidUuid((string) $tag->id)) {
            return false; // Invalid UUID → never detach
        }

        if (
            !method_exists($model, 'tags') &&
            !method_exists($model, 'detachTag') &&
            !method_exists($model, 'detachTags')
        ) {
            throw new RuntimeException(
                sprintf("Model %s does not expose 'tags()' relation nor detach*() method.", get_class($model)),
            );
        }

        if (method_exists($model, 'tags')) {
            $attached = $model
                ->tags()
                ->where('tags.id', $tag->id)
                ->exists();
            if (!$attached) {
                return false; // Wasn’t attached → no detach
            }
            return self::safeDetach($model, [$tag->id]) > 0;
        }

        return self::safeCustomDetach($model, [$tag->id]);
    }

    /**
     * Safe detach using belongsToMany->detach().
     * @param  string[] $ids
     * @return int number of rows affected
     */
    private static function safeDetach(Model $model, array $ids): int {
        $ids = array_values(array_filter($ids, fn($id) => is_string($id) && $id !== '' && self::isValidUuid($id)));
        if (empty($ids)) {
            return 0; // Prevents SQL IN ()
        }
        return (int) $model->tags()->detach($ids);
    }

    /**
     * Safe detach for custom methods (detachTag / detachTags).
     * Returns true if it attempted to detach something.
     * @param  string[] $ids
     */
    private static function safeCustomDetach(Model $model, array $ids): bool {
        $ids = array_values(array_filter($ids, fn($id) => is_string($id) && $id !== '' && self::isValidUuid($id)));
        if (empty($ids)) {
            return false;
        }

        if (method_exists($model, 'detachTag')) {
            $model->detachTag($ids);
            return true;
        }
        if (method_exists($model, 'detachTags')) {
            $model->detachTags($ids);
            return true;
        }

        return false;
    }
}
