// TO DO: ADD COLOR CODE TO EACH STATUS
// TO DO: ADD ICON TO EACH STATUS
// TO DO: ADD BOOLEAN IF IT CAN BE MANUALLY CHANGED OR NOT

export enum CabinStatusFilters {
    AVAILABLE = 'AVAILABLE',
    RESERVED = 'RESERVED',
    BOOKED = 'BOOKED',
    PARTIALY_BOOKED = 'PARTIALLY_BOOKED',
    CLOSED = 'CLOSED',
}

export enum CabinStatusOverrides {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  CLOSED = 'CLOSED',
}

// TO DO: DELETE THIS ENUM. CURRENTLY IS IN detail cabin Edit.tsx
export enum CabinStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  CLOSED = 'CLOSED',
}
