export enum TagEnum {
  STAFF = "STAFF", 
  ARTIST = "ARTISTS", 
  PRESS = "PRESS", 
  UNUSABLE = "UNUSABLE",
  NON_REV = "NON-REV", 
  POTENTIAL_NOSE = "POTENTIAL NOISE",
  NOT_ASSIGNED = "NOT ASSIGNED",
  ASSIGNED = "ASSIGNED"
}

export enum BookingTagEnum {
  NOT_ASSIGNE = "NOT ASSIGNED", 
  NEW = "NEW", 
  OVERDUE = "OVERDUE", 
  MISSING_INFO = "MISSING INFO",
  PAID = "PAID", 
  IN_MANIFEST = "IN MANIFEST"
}
