<?php

namespace App\Enums;

enum ErrorCode: string
{
  case BOOKING_LIMIT_EXCEEDED = 'BOOKING_LIMIT_EXCEEDED';
  case BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND';
  case ACCESS_DENIED = 'ACCESS_DENIED';
  case UNAUTHORIZED = 'UNAUTHORIZED';
  case AGE_RESTRICTION = 'AGE_RESTRICTION';
  case DOB_REQUIRED = 'DOB_REQUIRED';
  case CABIN_TYPE_NOT_ALLOWED = 'CABIN_TYPE_NOT_ALLOWED';
  case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
  case CART_EMPTY = 'CART_EMPTY';
  case CART_LOCKED = 'CART_LOCKED';
  case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
  case INVALID_TOKEN = 'INVALID_TOKEN';
  case RESERVATION_EXPIRED = 'RESERVATION_EXPIRED';
  case PASSENGER_SLOT_TAKEN = 'PASSENGER_SLOT_TAKEN';
  case ALREADY_HAS_INVITATION = 'ALREADY_HAS_INVITATION';
  case EMAIL_ALREADY_USED_IN_ANOTHER_BOOKING = 'EMAIL_ALREADY_USED_IN_ANOTHER_BOOKING';
  case PASSENGER_ORDER_TAKEN = 'PASSENGER_ORDER_TAKEN';
  case SINGLE_OCCUPANCY_BOOKING = 'SINGLE_OCCUPANCY_BOOKING';
  case CANNOT_INVITE_YOURSELF = 'CANNOT_INVITE_YOURSELF';
}
