<?php

namespace App\Enums;

enum ErrorCode: string
{
  case BOOKING_LIMIT_EXCEEDED = 'BOOKING_LIMIT_EXCEEDED';
  case BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND';
  case ACCESS_DENIED = 'ACCESS_DENIED';
  case UNAUTHORIZED = 'UNAUTHORIZED';
  case AGE_RESTRICTION = 'AGE_RESTRICTION';
  case DOB_REQUIRED = 'DOB_REQUIRED';
  case CABIN_TYPE_NOT_ALLOWED = 'CABIN_TYPE_NOT_ALLOWED';
  case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
  case CART_EMPTY = 'CART_EMPTY';
  case CART_LOCKED = 'CART_LOCKED';
  case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
  case INVALID_TOKEN = 'INVALID_TOKEN';
  case RESERVATION_EXPIRED = 'RESERVATION_EXPIRED';
}
